Repository alltheplaces/alltheplaces, pull requests merged in 2024-02, with the labels that each got.

#7339 bing_lee_au: uses DataDome so attempt requires_proxy=True
  locations/spiders/bing_lee_au.py
  locations/structured_data_spider.py
Labels: Bot protection: DataDome

#7340 bluepearl_pet_hospital_us: use proxy due to Cloudflare bot protection
  locations/spiders/bluepearl_pet_hospital_us.py
Labels: Bot protection: Cloudflare

#7592 Implement very basic bauspezi_de
  locations/spiders/bauspezi_de.py
Labels: Store finder: WP Go Maps
